version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/jwt-authentication
permissions:
  - object: /var/www/jwt-authentication
    pattern: "**"
    except: [artisan]
    owner: nginx
    group: nginx
    mode: 664
    type:
      - file
  - object: /var/www/jwt-authentication
    pattern: "**"
    owner: nginx
    group: nginx
    mode: 775
    type:
      - directory
  - object: /var/www/jwt-authentication
    pattern: "artisan"
    owner: nginx
    group: nginx
    mode: 775
    type:
      - file
hooks:
  AfterInstall:
    - location: deployment/bin/configure.sh
      timeout: 300
      runas: root
